export default {
      "id": 0,
      "banco": "",
      "agencia": "0",
      "conta": "0",
      "carteira": 0,
      "nome": "",
      "limite": 0,
      "utilizado": 0,
      "saldo": 0,
      "defasagem": 0,
      "descoberto": 0,
      "valor_operacao": 0,
      "valor_tarifa": 0,
      "taxa_juros": 0,
      "total_iof": 0,
      "total_juros": 0,
      "total_tarifas": 0,
      "remessa": 0,
      "retorno": 0
}